ALTER TABLE `Post`
  MODIFY `content` MEDIUMTEXT NOT NULL,
  ADD COLUMN `contentJson` JSON NULL,
  ADD COLUMN `contentFormat` ENUM('RICH_TEXT', 'PLAIN_TEXT') NOT NULL DEFAULT 'PLAIN_TEXT';

ALTER TABLE `PostDraft`
  MODIFY `content` MEDIUMTEXT NOT NULL,
  ADD COLUMN `contentJson` JSON NULL,
  ADD COLUMN `contentFormat` ENUM('RICH_TEXT', 'PLAIN_TEXT') NOT NULL DEFAULT 'PLAIN_TEXT';
